# Generated by Django 5.1.3 on 2024-12-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogpost_options_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
