# Generated by Django 5.1.3 on 2024-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogpost_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='blog_imgs/'),
        ),
    ]
