# Generated by Django 5.1.3 on 2024-12-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogpost_img_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
