# Generated by Django 5.0.7 on 2024-08-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img_url', models.URLField()),
                ('description', models.TextField()),
                ('project_url', models.URLField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
