# Generated by Django 5.1.3 on 2024-12-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img_url',
            field=models.ImageField(upload_to='project_imgs/'),
        ),
    ]
