# Generated by Django 5.1.3 on 2024-11-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.JSONField(blank=True, default=dict, help_text='JSON format', null=True)),
            ],
        ),
    ]
