# Generated by Django 5.1.3 on 2024-11-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0002_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
