# Generated by Django 5.1.3 on 2024-11-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0003_alter_timeline_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='type',
            field=models.CharField(choices=[('education', 'Education'), ('experience', 'Experience')], default='education', max_length=20),
        ),
    ]
